Enable cache flush after every -F iteration. Default : 0 (No cache flush)
ROCmSoftwarePlatform/rccl-tests pull request #76
Opened 2024-05-07 16:38 UTC by saurabhAMD

Enable instruction cache flush after every -F iteration. Default : 0 (No cache flush)

2024-05-07 16:43 UTC, nileshnegi commented on src/common.cu
> +                         :);
are the no. of these NOPs specific to MI300x?
also, can these be replaced by something like `s_nop 0xf`?

2024-05-07 17:08 UTC, saurabhAMD commented on src/common.cu
> +                         :);
I have used this as a reference for this command: https://github.com/ROCm/hipBLASLt/blob/84e55ed4cdad47089d3eeac0d7def923f133368a/clients/benchmarks/client_sequence.cpp#L39

2024-05-09 16:00 UTC, gilbertlee-amd commented on src/common.cu
> +    if(enable_cache_flush > 0 && (enable_cache_flush==1 || ((iter % enable_cache_flush) == 0))) {
if (enable_cache_flush > 0 && (iter % enable_cache_file == 0)) would suffice here.
1 divides everything.

2024-05-09 16:03 UTC, gilbertlee-amd commented on src/common.cu
> +      "[-F,--cache_flush <0/1>] \n\t"
This doesn't need to be just 0 or 1 though.

2024-05-09 16:06 UTC, nileshnegi commented on src/common.cu
> +                         :);
if you have a cache-flush verification mechanism, can you check if replacing these 16 `s_nop 0` with 1 `s_nop 0xf` is functionally similar?

2024-05-09 16:06 UTC, gilbertlee-amd requested changes

2024-05-09 16:06 UTC, gilbertlee-amd commented on src/common.cu
> +      hipDeviceProp_t deviceProps;
gpu_block3 shouldn't be queried / calculated per iteration to avoid unnecessary overhead

2024-05-09 16:09 UTC, nileshnegi commented on src/common.cu
> +    if(enable_cache_flush > 0 && (enable_cache_flush==1 || ((iter % enable_cache_flush) == 0))) {
also, is the idea to silently not run cache flushing if iterations are not divisible by the number of cache flush iterations? should there be a warning message? or failure to run?

2024-05-09 16:12 UTC, saurabhAMD commented on src/common.cu
> +    if(enable_cache_flush > 0 && (enable_cache_flush==1 || ((iter % enable_cache_flush) == 0))) {
The mod operation to enable cache flush after every -F iteration. Thus, I don't think any warning message is needed.

2024-05-10 15:57 UTC, saurabhAMD commented on src/common.cu
> +      hipDeviceProp_t deviceProps;
Thank you for your comment. Updated your suggestion in the latest commit.

2024-05-10 15:57 UTC, saurabhAMD commented on src/common.cu
> +      "[-F,--cache_flush <0/1>] \n\t"
Thank you for your comment. Updated your suggestion in the latest commit.

2024-05-13 15:41 UTC, gilbertlee-amd approved these changes

2024-05-13 15:41 UTC, merged